/*
 *        Filename: kludge.c
 *   Creation Date: 07/02/1996
 *          Author: Gabe Saporito
 *
 *     Description: The purpose of this file is to work around a problem found
 *                  when combining PRO*C (7.2.3?) with Sun C++ compilers.
 *                  Specifically, the code generated by PRO*C leaves unresolved
 *                  symbols at link time, because their prototypes do not match
 *                  what is in the library for them.  If the functions are
 *                  prototyped as 'extern "C",' then they link just fine.
 *                  However, the PRO*C preprocessor doesn't understand the
 *                  'extern "C"' syntax.  SOOO, what is going on here is, using
 *                  the C preprocessor, I have changed the references from
 *                  function_name to kldg_function_name.  Then, in this file, I
 *                  "stub out" the kldg functions to call the actual ones
 *                  (since in here I CAN use the extern "C" construct, because
 *                  I don't need PRO*C.
 *
 *       Functions: struct SQLDA *kldg_sqlald(int i,size_t j,size_t k)
 *                  void kldg_sqlclu(struct SQLDA *dap)
 *                  void kldg_sqlprc(unsigned long *lp,int *ip,int *jp)
 *                  void kldg_sqlcex(unsigned long *lp, struct sqlexd *p1,
 *                       const struct sqlcxp *p2)
 *
 *         Changes:
 *
 *            Date:   $Date: 07/02/1996 16:19:49 $
 *            Name: $Author: gabes $
 *        Revision:
 *     Description:
 */
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <ctype.h>
#include <errno.h>
#include <sys/types.h>
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>

#include <sqlca.h>
#include <sqlda.h>

extern "C" struct SQLDA *sqlald(int,size_t,size_t);
extern "C" void sqlclu(struct SQLDA *);
extern "C" void sqlprc(unsigned long *,int *,int *);
extern "C" void sqlcex(unsigned long *, struct sqlexd *, const struct sqlcxp *);

struct SQLDA *kldg_sqlald(int i,size_t j,size_t k)
{
	return(sqlald(i,j,k));
}

void kldg_sqlclu(struct SQLDA *dap)
{
	sqlclu(dap);
}

void kldg_sqlprc(unsigned long *lp,int *ip,int *jp)
{
	sqlprc(lp,ip,jp);
}

void kldg_sqlcex(unsigned long *lp, struct sqlexd *p1, const struct sqlcxp *p2)
{
	sqlcex(lp,p1,p2);
}
